CREATE DATABASE walmart_sales;
USE  walmart_sales;

CREATE TABLE sales (
Invoice_ID	varchar(30) not null primary key,
Branch	varchar(5) not null,
City varchar(50) not null,
Customer_type varchar(50) not null,
Gender	varchar(30) not null,
Product_line varchar(100) not null,	
Unit_price	float not null,
Quantity int not null,	
VAT	float,
Total	float,
Date date not null,
Time time not null,
Payment	varchar(50),
cogs float,	
Gross_margin_percentage	float,
Gross_income float,
Rating float
);

select * from sales;
-- What is the total revenue?
select round(sum(total),0) as total_revenue from sales;

-- What is the total quantity of products sold?
select sum(quantity) as total_quantity from sales;

-- Sales generated by each city?
select city, round(sum(total),2) as total_sales from sales
group by city
order by total_sales desc;

-- Avg Gross income of branch and city.
select round(avg(Gross_income),3) as avg_gross_income, branch, city
from sales 
group by branch, city
order by avg_gross_income desc;

-- Which product line generated highest revenue?
select product_line, round(sum(total),2) as total_sales
from sales 
group by product_line
order by total_sales desc
limit 1;

-- Which product line generated least revenue?
select product_line, round(sum(total),2) as total_sales
from sales 
group by product_line
order by total_sales asc
limit 1;

-- What is the avg unit price of each product line?
select Product_line, round(avg(unit_price), 2) as avg_price
from sales
group by product_line;

-- Total no. of products sold of each product line?
select Product_line, sum(Quantity) as quantity 
from sales
group by product_line
order by quantity desc;

-- How many distinct type of customer are present in the data?
select customer_type from sales 
group by customer_type;

-- What is the revenue generated by each customer type?
select Customer_type, round(sum(total),2) as total_sales
from sales 
group by Customer_type;

-- What is the revenue generated by different gender?
select Gender, round(sum(total),2) as total_sales
from sales 
group by Gender;

-- What is the average rating given by each customer type?
select Customer_type, round(avg(Rating),2) as avg_ratings
from sales 
group by Customer_type, Gender;

SELECT date,
MONTHNAME(date) AS month_name
FROM sales;

ALTER TABLE sales ADD COLUMN month_name VARCHAR(10);

UPDATE sales
SET month_name = MONTHNAME(date);

SET SQL_SAFE_UPDATES = 0;

SELECT date,
dayname(date) AS day_name
FROM sales;

alter table sales add column day_name varchar(20);

update sales
set day_name = dayname(date);

select extract(hour from time) as hour from sales;

alter table sales add column hour int;

update sales 
set hour = hour(time);

-- What are the monthly sales?
select month_name, round(sum(total),2) as monthly_sales 
from sales 
group by month_name
order by monthly_sales desc;

-- Which day of week generated highest revenue?
select day_name, sum(total) as daily_sales
from sales 
group by day_name
order by daily_sales desc
limit 1;

-- Which hour of the day generated highest revenue?
select hour,  round(sum(total),2) as hourly_sales
from sales
group by hour 
order by hourly_sales desc;

-- Which mode of payment generated highest revenue?
select Payment, round(sum(total),2) as mode_of_payment 
from sales 
group by Payment
order by mode_of_payment desc;

-- Which city generated highest gross income?
select round(sum(Gross_income),2) as total_income
, city from sales
group by city
order by total_income desc; 

alter table sales
add column day varchar(50);
update sales
set day = case 
      when day_name = 'Saturday' or day_name = 'Sunday' then 'Weekend'
      else 'Weekday'
      end;

-- Highest sales generated by weekdays vs weekend.
select day, round(sum(total),2) as day_sales
from sales
group by day
order by day_sales desc;

-- Which city has the largest tax percent/ VAT (Value Added Tax)?
select city, sum(vat) as total_tax from sales
group by city
order by total_tax desc
limit 1;

-- Which customer type pays the most in VAT?
select customer_type, sum(vat) as total_vat from sales
group by customer_type
order by total_vat desc;

-- What are the different modes of payment used by customer?
select payment from sales
group by payment;

-- Which mode of payment is mostly used by customer and what is the revenue generated by each of them?
select payment, sum(total) as total_sales from sales
group by payment
order by total_sales desc;

-- Which customer type buys the most?
select customer_type, sum(total) as total_sales
from sales
group by customer_type
order by total_sales desc;

-- Which gender generates most revenue?
select gender, sum(total) as total_sales
from sales
group by gender
order by total_sales desc;


